--- # Setup Linux desktop environment
- hosts: localhost
  connection: local
  become: yes

  vars:
    ssh_key_filename: id_rsa

  roles:
    - role: geerlingguy.java
      java_packages:
        - openjdk-11-jdk
        - openjdk-11-jre
    - role: geerlingguy.docker
    - role: don_rumata.ansible_role_install_snap
    - role: ngetchell.vscode
      vars:
        vscode_extension:
          - janjoerke.jenkins-pipeline-linter-connector
          - mechatroner.rainbow-csv
          - redhat.vscode-yaml
          - visualstudioexptteam.vscodeintellicode
          - esbenp.prettier-vscode
          - atlassian.atlascode
          - eamodio.gitlens
          - ms-azuretools.vscode-docker
          - vscoss.vscode-ansible
    - role: pixelart.chrome

  tasks:
  - name: install git
    apt:
      name: git
      state: latest
  - name: Install Spotify
    snap:
      name: spotify
      state: present
  - name: Install Android Studio
    snap:
      name: android-studio
      classic: yes
  - name: Install Opera
    snap:
      name: opera
      state: present
  - name: Install beekeeper
    snap:
      name: beekeeper-studio
  - name: Install postman
    snap:
      name: postman
      state: present
  - name: Install Slack
    snap:
      name: slack
      classic: yes
  - name: Install Skype
    snap:
      name: skype
      classic: yes
  - name: Install Teams for Linux
    snap:
      name: teams-for-linux
      state: present